version: "3.7"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PORTAL_AMBIENTAL_NEXT
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "5000:3000"
    networks:
      - PORTAL_AMBIENTAL_FRONT_NEXT_NET

networks:
  PORTAL_AMBIENTAL_FRONT_NEXT_NET:
